# Create a Logistic Regression to predict Absenteeism

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the Data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessing.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0     False     False     False      True                     289   
1     False     False     False     False                     118   
2     False     False     False      True                     179   
3      True     False     False     False                     279   
4     False     False     False      True                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## Create the targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median() , 1 , 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0     False     False     False      True                     289   
1     False     False     False     False                     118   
2     False     False     False      True                     179   
3      True     False     False     False                     279   
4     False     False     False      True                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 
                                            'Daily Work Load Average', 'Distance to Work'] , axis = 1)

In [9]:
data_with_targets is data_preprocessed

False

In [10]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0     False     False     False      True                     289   33   
1     False     False     False     False                     118   50   
2     False     False     False      True                     179   38   
3      True     False     False     False                     279   39   
4     False     False     False      True                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  \
0               30          0         2     1            7   
1               31          0         1     0            7   
2               31          0         0     0            7   
3               24          0         2     0            7   
4               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [11]:
unscaled_inputs = data_with_targets.drop(['Excessive Absenteeism'] , axis = 1)

## Standardize the Data

In [12]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [13]:
from sklearn.base import BaseEstimator , TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator , TransformerMixin):
    def __init__(self , columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self , X , y = None):
        self.scaler.fit(X[self.columns] , y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self , X , y = None , copy = None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]) , columns = self.columns)
        X_not_scaled = X.loc[: , ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled , X_scaled] , axis = 1)[init_col_order]

In [14]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [15]:
columns_to_scale = ['Transportation Expense','Age', 'Body Mass Index','Children', 'Pets', 'Month Value']

In [16]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [17]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\vrani\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'])

In [18]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [19]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0       False     False     False      True                1.005844 -0.536062   
1       False     False     False     False               -1.574681  2.130803   
2       False     False     False      True               -0.654143  0.248310   
3        True     False     False     False                0.854936  0.405184   
4       False     False     False      True                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695      True     False     False     False               -0.654143  0.562059   
696      True     False     False     False                0.040034 -1.320435   
697      True     False     False     False                1.624567 -1.320435   
698     False     False     False      True                0.190942 -0.692937   
699     False     False     False      True                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month Value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [20]:
scaled_inputs.shape

(700, 11)

## Split the data into train and test

Import the relevant libraries

In [21]:
from sklearn.model_selection import train_test_split

Split

In [ ]:
train_test_split(scaled_inputs , targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 439      True     False     False     False                0.190942  0.091435   
 405     False     False     False     False                0.190942  0.091435   
 462      True     False     False     False                0.568211 -0.065439   
 558      True     False     False     False               -0.654143 -1.006686   
 200     False     False      True     False                2.348925 -0.065439   
 ..        ...       ...       ...       ...                     ...       ...   
 159     False     False     False      True                1.036026  0.562059   
 415     False     False     False      True                2.213108 -0.849811   
 312     False     False     False     False                1.036026  0.562059   
 155     False     False     False      True                1.036026 -0.692937   
 544     False     False     False      True               -0.654143  0.248310   
 
      Body Mas

In [23]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs , targets , test_size = 0.2 , random_state = 42)

In [24]:
print(x_train.shape , y_train.shape)

(560, 11) (560,)


In [25]:
print(x_test.shape , y_test.shape)

(140, 11) (140,)


## Logistic regression with Sklearn

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

Training the Model

In [27]:
reg = LogisticRegression()

In [ ]:
reg.fit(x_train , y_train)

LogisticRegression()

In [29]:
reg.score(x_train , y_train)

0.7732142857142857

Finding the intercept and coefficients

In [30]:
reg.intercept_

array([-1.70293007])

In [31]:
reg.coef_

array([[ 2.9136209 ,  0.75484748,  3.09891742,  0.96486444,  0.65018629,
        -0.25112372,  0.25250206, -0.24004052,  0.39910996, -0.29389223,
         0.07441017]])

In [32]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [33]:
feature_names = unscaled_inputs.columns.values

In [34]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_names)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.913621
1                 Reason_2     0.754847
2                 Reason_3     3.098917
3                 Reason_4     0.964864
4   Transportation Expense     0.650186
5                      Age    -0.251124
6          Body Mass Index     0.252502
7                Education    -0.240041
8                 Children     0.399110
9                     Pets    -0.293892
10             Month Value     0.074410

In [35]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.702930
1                 Reason_1     2.913621
2                 Reason_2     0.754847
3                 Reason_3     3.098917
4                 Reason_4     0.964864
5   Transportation Expense     0.650186
6                      Age    -0.251124
7          Body Mass Index     0.252502
8                Education    -0.240041
9                 Children     0.399110
10                    Pets    -0.293892
11             Month Value     0.074410

Interpreting the Coefficients

In [36]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [37]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.702930    0.182149
1                 Reason_1     2.913621   18.423387
2                 Reason_2     0.754847    2.127287
3                 Reason_3     3.098917   22.173933
4                 Reason_4     0.964864    2.624432
5   Transportation Expense     0.650186    1.915898
6                      Age    -0.251124    0.777926
7          Body Mass Index     0.252502    1.287242
8                Education    -0.240041    0.786596
9                 Children     0.399110    1.490498
10                    Pets    -0.293892    0.745357
11             Month Value     0.074410    1.077249

In [38]:
summary_table.sort_values('Odds_ratio' , ascending = False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.098917   22.173933
1                 Reason_1     2.913621   18.423387
4                 Reason_4     0.964864    2.624432
2                 Reason_2     0.754847    2.127287
5   Transportation Expense     0.650186    1.915898
9                 Children     0.399110    1.490498
7          Body Mass Index     0.252502    1.287242
11             Month Value     0.074410    1.077249
8                Education    -0.240041    0.786596
6                      Age    -0.251124    0.777926
10                    Pets    -0.293892    0.745357
0                Intercept    -1.702930    0.182149

## Testing the Model

In [39]:
reg.score(x_test , y_test)

0.7714285714285715

In [40]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.82957126, 0.17042874],
       [0.85163998, 0.14836002],
       [0.79779583, 0.20220417],
       [0.593212  , 0.406788  ],
       [0.57365867, 0.42634133],
       [0.08041824, 0.91958176],
       [0.67595129, 0.32404871],
       [0.35568421, 0.64431579],
       [0.7163203 , 0.2836797 ],
       [0.74005176, 0.25994824],
       [0.86456635, 0.13543365],
       [0.67492732, 0.32507268],
       [0.26570587, 0.73429413],
       [0.44925745, 0.55074255],
       [0.72600362, 0.27399638],
       [0.4921817 , 0.5078183 ],
       [0.89459595, 0.10540405],
       [0.21441612, 0.78558388],
       [0.86703473, 0.13296527],
       [0.58401659, 0.41598341],
       [0.73026575, 0.26973425],
       [0.74411785, 0.25588215],
       [0.68178599, 0.31821401],
       [0.67957102, 0.32042898],
       [0.86082189, 0.13917811],
       [0.16084394, 0.83915606],
       [0.59430082, 0.40569918],
       [0.59675531, 0.40324469],
       [0.75996029, 0.24003971],
       [0.59941268, 0.40058732],
       [0.

In [41]:
predicted_proba.shape

(140, 2)

## Save the Model

In [42]:
import pickle

In [43]:
with open('model','wb') as file:
    pickle.dump(reg , file)

In [44]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler , file)